spring:
  application:
    name: edge-rtac
  liquibase:
    enabled: false
  jackson:
    default-property-inclusion: non_null
  cloud:
    openfeign:
      okhttp:
        enabled: true

management.endpoints.web.base-path: /admin
header.validation.x-okapi-tenant.exclude.base-paths: /admin,/swagger,/v2/api-docs

folio:
  system-user:  # This isn't actually used, but we get dependency injection errors from folio-spring-system-user if we don't have it
    username: dummy
    password: dummy
  environment: dev # Overridden at runtime in production, but causes folio-spring-system-user DI errors if it's not set
  tenant:
    validation:
      enabled: false
  client:
#    okapiUrl: http://localhost:9130
    tls:
      enabled: false
#      trustStorePath: ~/test/test.truststore.bcfks
#      trustStorePassword: "SecretPassword"
#      trustStoreType: BCFKS
logging:
  config: classpath:log4j2.xml

server:
  port: 8081
  error:
    include-message: always

security:
  store: ${secure_store:Ephemeral}
  props-location: ${secure_store_props:src/main/resources/ephemeral.properties}

token:
  capacity: ${token_cache_capacity:100}
  ttl-ms: ${token_cache_ttl_ms:3600000}
  fail-ttl-ms: ${null_token_cache_ttl_ms:30000}
